# create network
- name: create custom vpc network
  gce_net:
    name: "{{ vpc_name }}"
    mode: custom
    subnet_name: "{{ subnet_name }}"
    subnet_region: asia-northeast1
    ipv4_range: "{{ ipv4_range }}"
    state: present
    project_id: "{{ project_id }}"
    service_account_email: "{{ service_account_email }}"
    pem_file: "{{ credentials_file }}"

- name: create firewall rule (internal)
  gce_net:
    name: "{{ vpc_name }}"
    fwname: allow-internal
    allowed: tcp
    src_range: ['"{{ ipv4_range }}"']
    state: present
    project_id: "{{ project_id }}"
    service_account_email: "{{ service_account_email }}"
    pem_file: "{{ credentials_file }}"

- name: create firewall rule (lb-http)
  gce_net:
    name: "{{ vpc_name }}"
    fwname: allow-lb-http
    allowed: tcp:80
    src_range: ['130.211.0.0/22','35.191.0.0/16']
    state: present
    project_id: "{{ project_id }}"
    service_account_email: "{{ service_account_email }}"
    pem_file: "{{ credentials_file }}"
