- name: stop instance
  gce:
    instance_names: "{{ instance_names }}"
    zone: "{{ zone }}"
    state: stopped
    service_account_email: "{{ service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    project_id: "{{ project_id }}"

- name: create nginx image
  gce_img:
    name: "{{ instance_names }}-image"
    source: "{{ instance_names }}"
    zone: "{{ zone }}"
    state: present
    service_account_email: "{{ service_account_email }}"
    pem_file: "{{ credentials_file }}"
    project_id: "{{ project_id }}"
